class AlreadyExistsError(BaseException):
    pass


class NotFoundError(BaseException):
    pass
